export const MODULE_LABELS = {
  material: { 
    id: 'material',
    label: 'Material', 
    title: 'Material Innovation Ideas',
    desc: 'Material Innovation Ideas',
    subtitle: 'e.g., Polymers, Resins, Films, Laminates & more',
    examples: 'Polymers, Resins, Films, Laminates & more'
  },
  functional: { 
    id: 'functional',
    label: 'Functional', 
    title: 'Functional Innovation Ideas',
    desc: 'Functional Innovation Ideas',
    subtitle: 'e.g., Applicators, Dispensers, Caps and Closures & more',
    examples: 'Applicators, Dispensers, Caps & Closures'
  },
  aesthetic: { 
    id: 'aesthetic',
    label: 'Aesthetic', 
    title: 'Aesthetic Innovation Ideas',
    desc: 'Aesthetic Innovation Ideas',
    subtitle: 'e.g., Decoration, Embellishments, Printing, Coating & more',
    examples: 'Decoration, Embellishments, Printing, Coating'
  },
  others: { 
    id: 'others',
    label: 'Others', 
    title: 'Other Innovation Ideas',
    desc: 'Other Innovation Ideas',
    subtitle: 'Any other packaging-related developments beyond tubes',
    examples: 'Any other packaging-related developments'
  }
};

export const CATEGORY_LABELS = {
  1: { 
    num: 1,
    short: 'Commercialised', 
    full: 'Commercialised Innovations / Ideas', 
    sub: 'Capability Matrix (Mfg. Site)',
    iconId: '#icon-factory',
    className: 'cat-1'
  },
  2: { 
    num: 2,
    short: 'NDP / WIP', 
    full: 'NPD / Validation / WIP Project', 
    sub: 'Region / Unit Details',
    iconId: '#icon-flask',
    className: 'cat-2'
  },
  3: { 
    num: 3,
    short: 'Outside-In Ideas', 
    full: 'Outside-In Ideas', 
    sub: 'From Market / Agency / etc. (Countrywise)',
    iconId: '#icon-globe',
    className: 'cat-3'
  }
};

export const COUNTRY_CODE = {
  AFGHANISTAN: "AF", ALBANIA: "AL", ALGERIA: "DZ", ANDORRA: "AD", ANGOLA: "AO",
  ARGENTINA: "AR", ARMENIA: "AM", AUSTRALIA: "AU", AUSTRIA: "AT", AZERBAIJAN: "AZ",
  BAHAMAS: "BS", BAHRAIN: "BH", BANGLADESH: "BD", BARBADOS: "BB", BELARUS: "BY",
  BELGIUM: "BE", BELIZE: "BZ", BENIN: "BJ", BHUTAN: "BT", BOLIVIA: "BO",
  BRAZIL: "BR", BRUNEI: "BN", BULGARIA: "BG", BURKINA_FASO: "BF", BURUNDI: "BI",
  CABO_VERDE: "CV", CAMBODIA: "KH", CAMEROON: "CM", CANADA: "CA", CENTRAL_AFRICAN_REPUBLIC: "CF",
  CHAD: "TD", CHILE: "CL", CHINA: "CN", COLOMBIA: "CO", COMOROS: "KM",
  CONGO: "CG", COSTA_RICA: "CR", CROATIA: "HR", CUBA: "CU", CYPRUS: "CY",
  CZECH_REPUBLIC: "CZ", DENMARK: "DK", DJIBOUTI: "DJ", DOMINICAN_REPUBLIC: "DO", ECUADOR: "EC",
  EGYPT: "EG", EL_SALVADOR: "SV", EQUATORIAL_GUINEA: "GQ", ERITREA: "ER", ESTONIA: "EE",
  ESWATINI: "SZ", ETHIOPIA: "ET", EUROPE: "EU", FIJI: "FJ", FINLAND: "FI",
  FRANCE: "FR", GABON: "GA", GAMBIA: "GM", GEORGIA: "GE", GERMANY: "DE",
  GHANA: "GH", GREECE: "GR", GRENADA: "GD", GUATEMALA: "GT", GUINEA: "GN",
  GUINEA_BISSAU: "GW", GUYANA: "GY", HAITI: "HT", HONDURAS: "HN", HONG_KONG: "HK",
  HUNGARY: "HU", ICELAND: "IS", INDIA: "IN", INDONESIA: "ID", IRAN: "IR",
  IRAQ: "IQ", IRELAND: "IE", ISRAEL: "IL", ITALY: "IT", IVORY_COAST: "CI",
  JAMAICA: "JM", JAPAN: "JP", JORDAN: "JO", KAZAKHSTAN: "KZ", KENYA: "KE",
  KIRIBATI: "KI", KUWAIT: "KW", KYRGYZSTAN: "KG", LAOS: "LA", LATVIA: "LV",
  LEBANON: "LB", LESOTHO: "LS", LIBERIA: "LR", LIBYA: "LY", LIECHTENSTEIN: "LI",
  LITHUANIA: "LT", LUXEMBOURG: "LU", MADAGASCAR: "MG", MALAWI: "MW", MALAYSIA: "MY",
  MALDIVES: "MV", MALI: "ML", MALTA: "MT", MAURITANIA: "MR", MAURITIUS: "MU",
  MEXICO: "MX", MOLDOVA: "MD", MONACO: "MC", MONGOLIA: "MN", MONTENEGRO: "ME",
  MOROCCO: "MA", MOZAMBIQUE: "MZ", MYANMAR: "MM", NAMIBIA: "NA", NEPAL: "NP",
  NETHERLANDS: "NL", NEW_ZEALAND: "NZ", NICARAGUA: "NI", NIGER: "NE", NIGERIA: "NG",
  NORTH_KOREA: "KP", NORTH_MACEDONIA: "MK", NORWAY: "NO", OMAN: "OM", PAKISTAN: "PK",
  PALAU: "PW", PANAMA: "PA", PAPUA_NEW_GUINEA: "PG", PARAGUAY: "PY", PERU: "PE",
  PHILIPPINES: "PH", POLAND: "PL", PORTUGAL: "PT", QATAR: "QA", ROMANIA: "RO",
  RUSSIA: "RU", RWANDA: "RW", SAMOA: "WS", SAN_MARINO: "SM", SAUDI_ARABIA: "SA",
  SENEGAL: "SN", SERBIA: "RS", SIERRA_LEONE: "SL", SINGAPORE: "SG", SLOVAKIA: "SK",
  SLOVENIA: "SI", SOMALIA: "SO", SOUTH_AFRICA: "ZA", SOUTH_KOREA: "KR", SOUTH_SUDAN: "SS",
  SPAIN: "ES", SRI_LANKA: "LK", SUDAN: "SD", SURINAME: "SR", SWEDEN: "SE",
  SWITZERLAND: "CH", SYRIA: "SY", TAIWAN: "TW", TAJIKISTAN: "TJ", TANZANIA: "TZ",
  THAILAND: "TH", TIMOR_LESTE: "TL", TOGO: "TG", TONGA: "TO", TRINIDAD_AND_TOBAGO: "TT",
  TUNISIA: "TN", TURKEY: "TR", TURKMENISTAN: "TM", TUVALU: "TV", UAE: "AE",
  UGANDA: "UG", UK: "GB", UKRAINE: "UA", UNKNOWN: "UN", URUGUAY: "UY",
  USA: "US", UZBEKISTAN: "UZ", VANUATU: "VU", VENEZUELA: "VE", VIETNAM: "VN",
  YEMEN: "YE", ZAMBIA: "ZM", ZIMBABWE: "ZW"
};

export const COUNTRY_OPTIONS = [
  { value: "AFGHANISTAN", label: "Afghanistan" },
  { value: "ALBANIA", label: "Albania" },
  { value: "ALGERIA", label: "Algeria" },
  { value: "ANDORRA", label: "Andorra" },
  { value: "ANGOLA", label: "Angola" },
  { value: "ANTIGUA_AND_BARBUDA", label: "Antigua and Barbuda" },
  { value: "ARGENTINA", label: "Argentina" },
  { value: "ARMENIA", label: "Armenia" },
  { value: "AUSTRALIA", label: "Australia" },
  { value: "AUSTRIA", label: "Austria" },
  { value: "AZERBAIJAN", label: "Azerbaijan" },
  { value: "BAHAMAS", label: "Bahamas" },
  { value: "BAHRAIN", label: "Bahrain" },
  { value: "BANGLADESH", label: "Bangladesh" },
  { value: "BARBADOS", label: "Barbados" },
  { value: "BELARUS", label: "Belarus" },
  { value: "BELGIUM", label: "Belgium" },
  { value: "BELIZE", label: "Belize" },
  { value: "BENIN", label: "Benin" },
  { value: "BHUTAN", label: "Bhutan" },
  { value: "BOLIVIA", label: "Bolivia" },
  { value: "BOSNIA", label: "Bosnia & Herzegovina" },
  { value: "BOTSWANA", label: "Botswana" },
  { value: "BRAZIL", label: "Brazil" },
  { value: "BRUNEI", label: "Brunei" },
  { value: "BULGARIA", label: "Bulgaria" },
  { value: "BURKINA_FASO", label: "Burkina Faso" },
  { value: "BURUNDI", label: "Burundi" },
  { value: "CABO_VERDE", label: "Cabo Verde" },
  { value: "CAMBODIA", label: "Cambodia" },
  { value: "CAMEROON", label: "Cameroon" },
  { value: "CANADA", label: "Canada" },
  { value: "CENTRAL_AFRICAN_REPUBLIC", label: "Central African Republic" },
  { value: "CHAD", label: "Chad" },
  { value: "CHILE", label: "Chile" },
  { value: "CHINA", label: "China" },
  { value: "COLOMBIA", label: "Colombia" },
  { value: "COMOROS", label: "Comoros" },
  { value: "CONGO", label: "Congo" },
  { value: "COSTA_RICA", label: "Costa Rica" },
  { value: "CROATIA", label: "Croatia" },
  { value: "CUBA", label: "Cuba" },
  { value: "CYPRUS", label: "Cyprus" },
  { value: "CZECH_REPUBLIC", label: "Czech Republic" },
  { value: "DENMARK", label: "Denmark" },
  { value: "DJIBOUTI", label: "Djibouti" },
  { value: "DOMINICAN_REPUBLIC", label: "Dominican Republic" },
  { value: "ECUADOR", label: "Ecuador" },
  { value: "EGYPT", label: "Egypt" },
  { value: "EL_SALVADOR", label: "El Salvador" },
  { value: "EQUATORIAL_GUINEA", label: "Equatorial Guinea" },
  { value: "ERITREA", label: "Eritrea" },
  { value: "ESTONIA", label: "Estonia" },
  { value: "ESWATINI", label: "Eswatini" },
  { value: "ETHIOPIA", label: "Ethiopia" },
  { value: "EUROPE", label: "Europe" },
  { value: "FIJI", label: "Fiji" },
  { value: "FINLAND", label: "Finland" },
  { value: "FRANCE", label: "France" },
  { value: "GABON", label: "Gabon" },
  { value: "GAMBIA", label: "Gambia" },
  { value: "GEORGIA", label: "Georgia" },
  { value: "GERMANY", label: "Germany" },
  { value: "GHANA", label: "Ghana" },
  { value: "GREECE", label: "Greece" },
  { value: "GRENADA", label: "Grenada" },
  { value: "GUATEMALA", label: "Guatemala" },
  { value: "GUINEA", label: "Guinea" },
  { value: "GUINEA_BISSAU", label: "Guinea-Bissau" },
  { value: "GUYANA", label: "Guyana" },
  { value: "HAITI", label: "Haiti" },
  { value: "HONDURAS", label: "Honduras" },
  { value: "HONG_KONG", label: "Hong Kong" },
  { value: "HUNGARY", label: "Hungary" },
  { value: "ICELAND", label: "Iceland" },
  { value: "INDIA", label: "India" },
  { value: "INDONESIA", label: "Indonesia" },
  { value: "IRAN", label: "Iran" },
  { value: "IRAQ", label: "Iraq" },
  { value: "IRELAND", label: "Ireland" },
  { value: "ISRAEL", label: "Israel" },
  { value: "ITALY", label: "Italy" },
  { value: "IVORY_COAST", label: "Ivory Coast" },
  { value: "JAMAICA", label: "Jamaica" },
  { value: "JAPAN", label: "Japan" },
  { value: "JORDAN", label: "Jordan" },
  { value: "KAZAKHSTAN", label: "Kazakhstan" },
  { value: "KENYA", label: "Kenya" },
  { value: "KIRIBATI", label: "Kiribati" },
  { value: "KUWAIT", label: "Kuwait" },
  { value: "KYRGYZSTAN", label: "Kyrgyzstan" },
  { value: "LAOS", label: "Laos" },
  { value: "LATVIA", label: "Latvia" },
  { value: "LEBANON", label: "Lebanon" },
  { value: "LESOTHO", label: "Lesotho" },
  { value: "LIBERIA", label: "Liberia" },
  { value: "LIBYA", label: "Libya" },
  { value: "LIECHTENSTEIN", label: "Liechtenstein" },
  { value: "LITHUANIA", label: "Lithuania" },
  { value: "LUXEMBOURG", label: "Luxembourg" },
  { value: "MADAGASCAR", label: "Madagascar" },
  { value: "MALAWI", label: "Malawi" },
  { value: "MALAYSIA", label: "Malaysia" },
  { value: "MALDIVES", label: "Maldives" },
  { value: "MALI", label: "Mali" },
  { value: "MALTA", label: "Malta" },
  { value: "MAURITANIA", label: "Mauritania" },
  { value: "MAURITIUS", label: "Mauritius" },
  { value: "MEXICO", label: "Mexico" },
  { value: "MOLDOVA", label: "Moldova" },
  { value: "MONACO", label: "Monaco" },
  { value: "MONGOLIA", label: "Mongolia" },
  { value: "MONTENEGRO", label: "Montenegro" },
  { value: "MOROCCO", label: "Morocco" },
  { value: "MOZAMBIQUE", label: "Mozambique" },
  { value: "MYANMAR", label: "Myanmar" },
  { value: "NAMIBIA", label: "Namibia" },
  { value: "NEPAL", label: "Nepal" },
  { value: "NETHERLANDS", label: "Netherlands" },
  { value: "NEW_ZEALAND", label: "New Zealand" },
  { value: "NICARAGUA", label: "Nicaragua" },
  { value: "NIGER", label: "Niger" },
  { value: "NIGERIA", label: "Nigeria" },
  { value: "NORTH_KOREA", label: "North Korea" },
  { value: "NORTH_MACEDONIA", label: "North Macedonia" },
  { value: "NORWAY", label: "Norway" },
  { value: "OMAN", label: "Oman" },
  { value: "PAKISTAN", label: "Pakistan" },
  { value: "PALAU", label: "Palau" },
  { value: "PANAMA", label: "Panama" },
  { value: "PAPUA_NEW_GUINEA", label: "Papua New Guinea" },
  { value: "PARAGUAY", label: "Paraguay" },
  { value: "PERU", label: "Peru" },
  { value: "PHILIPPINES", label: "Philippines" },
  { value: "POLAND", label: "Poland" },
  { value: "PORTUGAL", label: "Portugal" },
  { value: "QATAR", label: "Qatar" },
  { value: "ROMANIA", label: "Romania" },
  { value: "RUSSIA", label: "Russia" },
  { value: "RWANDA", label: "Rwanda" },
  { value: "SAMOA", label: "Samoa" },
  { value: "SAN_MARINO", label: "San Marino" },
  { value: "SAUDI_ARABIA", label: "Saudi Arabia" },
  { value: "SENEGAL", label: "Senegal" },
  { value: "SERBIA", label: "Serbia" },
  { value: "SIERRA_LEONE", label: "Sierra Leone" },
  { value: "SINGAPORE", label: "Singapore" },
  { value: "SLOVAKIA", label: "Slovakia" },
  { value: "SLOVENIA", label: "Slovenia" },
  { value: "SOMALIA", label: "Somalia" },
  { value: "SOUTH_AFRICA", label: "South Africa" },
  { value: "SOUTH_KOREA", label: "South Korea" },
  { value: "SOUTH_SUDAN", label: "South Sudan" },
  { value: "SPAIN", label: "Spain" },
  { value: "SRI_LANKA", label: "Sri Lanka" },
  { value: "SUDAN", label: "Sudan" },
  { value: "SURINAME", label: "Suriname" },
  { value: "SWEDEN", label: "Sweden" },
  { value: "SWITZERLAND", label: "Switzerland" },
  { value: "SYRIA", label: "Syria" },
  { value: "TAIWAN", label: "Taiwan" },
  { value: "TAJIKISTAN", label: "Tajikistan" },
  { value: "TANZANIA", label: "Tanzania" },
  { value: "THAILAND", label: "Thailand" },
  { value: "TIMOR_LESTE", label: "Timor-Leste" },
  { value: "TOGO", label: "Togo" },
  { value: "TONGA", label: "Tonga" },
  { value: "TRINIDAD_AND_TOBAGO", label: "Trinidad and Tobago" },
  { value: "TUNISIA", label: "Tunisia" },
  { value: "TURKEY", label: "Turkey" },
  { value: "TURKMENISTAN", label: "Turkmenistan" },
  { value: "TUVALU", label: "Tuvalu" },
  { value: "UAE", label: "United Arab Emirates" },
  { value: "UGANDA", label: "Uganda" },
  { value: "UK", label: "United Kingdom" },
  { value: "UKRAINE", label: "Ukraine" },
  { value: "UNKNOWN", label: "Unknown" },
  { value: "URUGUAY", label: "Uruguay" },
  { value: "USA", label: "United States" },
  { value: "UZBEKISTAN", label: "Uzbekistan" },
  { value: "VANUATU", label: "Vanuatu" },
  { value: "VENEZUELA", label: "Venezuela" },
  { value: "VIETNAM", label: "Vietnam" },
  { value: "YEMEN", label: "Yemen" },
  { value: "ZAMBIA", label: "Zambia" },
  { value: "ZIMBABWE", label: "Zimbabwe" }
];

export function buildRefNo(row) {
  if (!row) return 'M--';
  const year = row.d_created_at
    ? new Date(row.d_created_at).getFullYear().toString().slice(-2)
    : new Date().getFullYear().toString().slice(-2);
  const cc = COUNTRY_CODE[row.s_country] || 'XX';
  const padId = String(row.n_id || 0).padStart(4, '0');
  return `M${year}${cc}${padId}`;
}

export function esc(str) {
  if (str == null) return '';
  return String(str);
}
